//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Member()
        {
            this.tbl_Movie = new HashSet<tbl_Movie>();
            this.Status = MemberStatus.Open;          
        }
    
        public int Member_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string CSN { get; set; }
        public Nullable<EntityFramework_Project.MemberStatus> Status { get; set; }
        public Nullable<int> HK_ID { get; set; }
    
        public virtual tbl_HemmaKväll tbl_HemmaKväll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Movie> tbl_Movie { get; set; }
    }
}
