//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movie
    {
        public int Movie_ID { get; set; }
        public Nullable<EntityFramework_Project.MovieStatus> Movie_Status { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<EntityFramework_Project.Genre> Genre { get; set; }
        public string Length { get; set; }
        public string Titel { get; set; }
        public Nullable<int> HemmaKväll_ID { get; set; }
    
        public virtual tbl_HemmaKväll tbl_HemmaKväll { get; set; }
        public virtual tbl_Member tbl_Member { get; set; }
    }
}
